corrections

diff --git a/ubuntu/etc/init.d/jvpn b/ubuntu/etc/init.d/jvpn
--- a/ubuntu/etc/init.d/jvpn
+++ b/ubuntu/etc/init.d/jvpn
@@ -43,12 +43,13 @@ PIDFILE=$PREFIX/var/run/$NAME/pid
 # Read configuration variable file if it is present
 [ -r $PREFIX/etc/default/$NAME ] && . $PREFIX/etc/default/$NAME
 
+# DAEMON_ARGS="-c $PREFIX/etc/jvpn/$CONFIG --starthook /usr/local/var/lib/jvpn/sbin/connect_hook.sh --endhook /usr/local/var/lib/jvpn/sbin/disconnect_hook.sh"
 DAEMON_ARGS="-c $PREFIX/etc/jvpn/$CONFIG"
 # Check config
 if [ -z "$JVPN_CONFIG_DONE" ]
 then
-	echo "Warning: jvpn not configured, edit config file in /etc/default/$NAME." 1>&2
-        exit 0
+    echo "Warning: jvpn not configured, edit config file in /etc/default/$NAME." 1>&2
+    exit 0
 fi
 
 # Load the VERBOSE setting and other rcS variables
@@ -63,48 +64,53 @@ fi
 #
 do_start()
 {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
 
-        if [ -r $PIDFILE ] # file present means disconnect_hook need to be called
-        then
-            if ps $(cat $PIDFILE) 2>&1 > /dev/null
-            then
-                do_status
-                exit -1;
-            fi
-        fi
+    if [ -e $PREFIX/var/lib/jvpn/forward ]
+    then
+        rm -f $PREFIX/var/lib/jvpn/forward
+    fi
 
-	start-stop-daemon --start --quiet --user $DAEMONUSER --exec $DAEMON --test \
-	    || return 1
-
-	start-stop-daemon --start --quiet --background \
-            --no-close \
-            --make-pidfile --pidfile $PIDFILE \
-            --user $DAEMONUSER --chuid $DAEMONUSER \
-            --exec $DAEMON -- \
-	    -c $PREFIX/etc/jvpn/$CONFIG \
-            --pid_file $PIDFILE \
-	    $DAEMON_ARGS \
-            2>&1 > /tmp/jvpnxx.log \
-	    || return 2
-
-        echo waiting for jvpn connect_hook >&2
-        sleep 10s
+    if [ -r $PIDFILE ] # file present means disconnect_hook need to be called
+    then
         if ps $(cat $PIDFILE) 2>&1 > /dev/null
         then
-            $PREFIX/var/lib/jvpn/sbin/connect_hook.sh
-        else
-            if [ -e $PIDFILE ]
-            then
-                rm -f $PIDFILE
-            fi
-            echo jvn service failed to start. >&2
-            exit -1
+            do_status
+            exit -1;
         fi
-        exit 0
+    fi
+
+    start-stop-daemon --start --quiet --user $DAEMONUSER --exec $DAEMON --test \
+	|| return 1
+
+    start-stop-daemon --start --quiet --background \
+        --no-close \
+        --make-pidfile --pidfile $PIDFILE \
+        --user $DAEMONUSER --chuid $DAEMONUSER \
+        --exec $DAEMON -- \
+	-c $PREFIX/etc/jvpn/$CONFIG \
+        --pid_file $PIDFILE \
+	$DAEMON_ARGS \
+        2>&1 > /tmp/jvpnxx.log \
+	|| return 2
+
+    echo waiting for jvpn connect_hook >&2
+    sleep 10s
+    if ps $(cat $PIDFILE) 2>&1 > /dev/null
+    then
+        $PREFIX/var/lib/jvpn/sbin/connect_hook.sh
+    else
+        if [ -e $PIDFILE ]
+        then
+            rm -f $PIDFILE
+        fi
+        echo jvn service failed to start. >&2
+        exit -1
+    fi
+    exit 0
 }
 
 #
@@ -112,84 +118,84 @@ do_start()
 #
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon -n $NAME -v --stop --quiet --retry=TERM/30/KILL/5 --user $DAEMONUSER --exec $DAEMON
-        if [ -r $PIDFILE ] # file present means disconnect_hook need to be called
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon -n $NAME -v --stop --quiet --retry=TERM/30/KILL/5 --user $DAEMONUSER --exec $DAEMON
+    if [ -r $PIDFILE ] # file present means disconnect_hook need to be called
+    then
+        if ps $(cat $PIDFILE) 2>&1 > /dev/null
         then
-            if ps $(cat $PIDFILE) 2>&1 > /dev/null
-            then
-                kill -TERM $(cat $PIDFILE)
-            fi
-            if ps $(cat $PIDFILE) 2>&1 > /dev/null
-            then
-                sleep 7s;
-                kill -KILL $(cat $PIDFILE)
-            fi
-            rm -f $PIDFILE
-            $PREFIX/var/lib/jvpn/sbin/disconnect_hook.sh
-            exit 0
-        else
-            exit -1
+            kill -TERM $(cat $PIDFILE)
         fi
+        if ps $(cat $PIDFILE) 2>&1 > /dev/null
+        then
+            sleep 7s;
+            kill -KILL $(cat $PIDFILE)
+        fi
+        rm -f $PIDFILE
+        $PREFIX/var/lib/jvpn/sbin/disconnect_hook.sh
+        exit 0
+    else
+        exit -1
+    fi
 }
 
 do_status()
 {
-	# Return
-        if [ -r $PIDFILE ] &&
-            ps h -l $(cat $PIDFILE)
-        then
-            echo instance of $NAME is running with pid $(cat $PIDFILE)...
-        else
-            echo no instance of $NAME is running...
-            exit 3
-        fi
+    # Return
+    if [ -r $PIDFILE ] &&
+        ps h -l $(cat $PIDFILE)
+    then
+        echo instance of $NAME is running with pid $(cat $PIDFILE)...
+    else
+        echo no instance of $NAME is running...
+        exit 3
+    fi
 }
 
 case "$1" in
-  start)
+    start)
 	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 	do_start
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
-  stop)
+    stop)
 	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
-  status)
+    status)
 	[ "$VERBOSE" != no ] && log_daemon_msg "Status $DESC" "$NAME"
 	do_status
         ;;
-  restart|force-reload)
+    restart|force-reload)
 	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
-	  0|1)
+	    0|1)
 		do_start
 		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+		    0) log_end_msg 0 ;;
+		    1) log_end_msg 1 ;; # Old process is still running
+		    *) log_end_msg 1 ;; # Failed to start
 		esac
 		;;
-	  *)
+	    *)
 	  	# Failed to stop
 		log_end_msg 1
 		;;
 	esac
 	;;
-  *)
+    *)
 	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
 	exit 3
 	;;
